### ISSUE TITLE
Use new Console REST API for peer register and unregister

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#124]
Now Vagrant Subutai plugin uses following REST API for peer register and unregister.
Because following REST API is deprecated.

```
/rest/v1/hub/unregister?sptoken=
/rest/v1/hub/register?sptoken=
```

We should use new Console REST API:

```
/rest/v1/bazaar/unregister?sptoken=
/rest/v1/bazaar/register?sptoken=
```

**Comment by jadilet** [comment]
How to test:

Use following user parameters in `vagrant-subutai.yml`
```
SUBUTAI_ENV: master
```
Do following commands:

```
vagrant init subutai/stretch-master
vagrant up
vagrant subutai register
vagrant subutai unregister
```

**Comment by Almansherov** [comment]
Followed the steps above^
Ended up with working functionality:


![image](https://user-images.githubusercontent.com/32430693/46394505-2b656d80-c69e-11e8-824c-ff6b5f69c8e3.png)

Implemented on master

**Comment by Almansherov** [comment]
However, when I updated the vagrant subutai plugin it stopped working. It was mentioned that the reason is because bazaar side changes were not merged into master yet. 
So, putting the issue back to backlog. 

![image 1](https://user-images.githubusercontent.com/32430693/46400893-58228080-c6b0-11e8-8b6a-1c4776b3e7b4.png)

**Comment by Almansherov** [comment]
Fixed in master:

![image](https://user-images.githubusercontent.com/32430693/50505946-f1f19380-0a3b-11e9-9b68-d9c0395a8f37.png)

**Comment by Almansherov** [comment]
Fixed in prod
